// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace datamodel
{
    using Newtonsoft.Json;

    using System.Linq;

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class AdDbContext : System.Data.Entity.DbContext, IAdDbContext
    {
        public System.Data.Entity.DbSet<Admin> Admins { get; set; } // Admin
        public System.Data.Entity.DbSet<Advertiser> Advertisers { get; set; } // Advertiser
        public System.Data.Entity.DbSet<AdvertisingCompany> AdvertisingCompanies { get; set; } // AdvertisingCompany
        public System.Data.Entity.DbSet<Manager> Managers { get; set; } // Manager
        public System.Data.Entity.DbSet<Partner> Partners { get; set; } // Partner
        public System.Data.Entity.DbSet<User> Users { get; set; } // User
        public System.Data.Entity.DbSet<WebMaster> WebMasters { get; set; } // WebMaster

        static AdDbContext()
        {
            System.Data.Entity.Database.SetInitializer<AdDbContext>(null);
            AdDbContextStaticPartial(); // Create the following method in your partial class: private static void AdDbContextStaticPartial() { }
        }

        public AdDbContext()
            : base("Name=db")
        {
            InitializePartial();
        }

        public AdDbContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }

        public AdDbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public AdDbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public AdDbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new AdminConfiguration());
            modelBuilder.Configurations.Add(new AdvertiserConfiguration());
            modelBuilder.Configurations.Add(new AdvertisingCompanyConfiguration());
            modelBuilder.Configurations.Add(new ManagerConfiguration());
            modelBuilder.Configurations.Add(new PartnerConfiguration());
            modelBuilder.Configurations.Add(new UserConfiguration());
            modelBuilder.Configurations.Add(new WebMasterConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new AdminConfiguration(schema));
            modelBuilder.Configurations.Add(new AdvertiserConfiguration(schema));
            modelBuilder.Configurations.Add(new AdvertisingCompanyConfiguration(schema));
            modelBuilder.Configurations.Add(new ManagerConfiguration(schema));
            modelBuilder.Configurations.Add(new PartnerConfiguration(schema));
            modelBuilder.Configurations.Add(new UserConfiguration(schema));
            modelBuilder.Configurations.Add(new WebMasterConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
}
// </auto-generated>
