// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace datamodel
{
    using Newtonsoft.Json;

    // AdvertisingCompany
    [Table("AdvertisingCompany", Schema = "comp")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.29.1.0")]
    public partial class AdvertisingCompany
    {

        ///<summary>
        /// Идентификатор
        ///</summary>
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Column(@"Id", Order = 1, TypeName = "int")]
        [Index(@"PK_AdvertisingCompany", 1, IsUnique = true, IsClustered = true)]
        [Required]
        [Key]
        [Display(Name = "Id")]
        public int Id { get; set; } // Id (Primary key)

        ///<summary>
        /// Наименование
        ///</summary>
        [Column(@"Name", Order = 2, TypeName = "varchar")]
        [Index(@"UK_AdvertisingCompany#Name", 1, IsUnique = true, IsClustered = false)]
        [Required]
        [MaxLength(255)]
        [StringLength(255)]
        [Display(Name = "Name")]
        public string Name { get; set; } // Name (length: 255)

        ///<summary>
        /// Дата создания
        ///</summary>
        [Column(@"CreationDate", Order = 3, TypeName = "datetimeoffset")]
        [Required]
        [Display(Name = "Creation date")]
        public System.DateTimeOffset CreationDate { get; set; } // CreationDate

        ///<summary>
        /// Активная
        ///</summary>
        [Column(@"IsActive", Order = 4, TypeName = "bit")]
        [Required]
        [Display(Name = "Is active")]
        public bool IsActive { get; set; } // IsActive

        ///<summary>
        /// Кем создана
        ///</summary>
        [Column(@"CreatedBy", Order = 5, TypeName = "int")]
        [Required]
        [Display(Name = "Created by")]
        public int CreatedBy { get; set; } // CreatedBy

        // Foreign keys

        [JsonIgnore]
        /// <summary>
        /// Parent Advertiser pointed by [AdvertisingCompany].([CreatedBy]) (FK_AdvertisingCompany_Advertizer)
        /// </summary>
        [ForeignKey("CreatedBy"), Required] public virtual Advertiser Advertiser { get; set; } // FK_AdvertisingCompany_Advertizer

        public AdvertisingCompany()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
